export const PERMISSIONS = {
  LAB_CATALOG_WRITE: 'LAB_CATALOG_WRITE',
  LAB_ORDER_WRITE: 'LAB_ORDER_WRITE',
  LAB_RESULTS_WRITE: 'LAB_RESULTS_WRITE',
  LAB_RESULTS_VERIFY: 'LAB_RESULTS_VERIFY',
  LAB_REPORT_PUBLISH: 'LAB_REPORT_PUBLISH',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
