/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email/password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get feature flags for current user scope */
        get: operations["getMyFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search patients */
        get: operations["listPatients"];
        put?: never;
        /** Register a new patient */
        post: operations["createPatient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get patient by id */
        get: operations["getPatientById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search encounters */
        get: operations["listEncounters"];
        put?: never;
        /** Create encounter */
        post: operations["createEncounter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get encounter by id */
        get: operations["getEncounterById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}/prep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get encounter prep data */
        get: operations["getEncounterPrep"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}/main": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get encounter main data */
        get: operations["getEncounterMain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:start-prep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start encounter preparation */
        post: operations["startEncounterPrep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:save-prep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save encounter prep data by encounter type */
        post: operations["saveEncounterPrep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:save-main": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save encounter main data by encounter type */
        post: operations["saveEncounterMain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:start-main": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start encounter main workflow */
        post: operations["startEncounterMain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize encounter */
        post: operations["finalizeEncounter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate/publish encounter document */
        post: operations["documentEncounter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get document metadata by id */
        get: operations["getDocumentById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentId}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download rendered PDF bytes */
        get: operations["getDocumentFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id?: string;
            email?: string;
            name?: string;
            tenantId?: string;
        };
        CreatePatientDto: {
            name: string;
            /** Format: date */
            dob?: string;
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            phone?: string;
        };
        Patient: components["schemas"]["CreatePatientDto"] & {
            id: string;
            /** @example REG-00000001 */
            regNo: string;
            tenantId?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ListPatientsResponse: {
            data?: components["schemas"]["Patient"][];
            total?: number;
        };
        CreateEncounterDto: {
            /** Format: uuid */
            patientId: string;
            /** @enum {string} */
            type: "LAB" | "RAD" | "OPD" | "BB" | "IPD";
            /** Format: date-time */
            startedAt?: string;
        };
        Encounter: components["schemas"]["CreateEncounterDto"] & {
            id: string;
            tenantId: string;
            /** @example OPD-2026-000001 */
            encounterCode: string;
            /** @enum {string} */
            status: "CREATED" | "PREP" | "IN_PROGRESS" | "FINALIZED" | "DOCUMENTED";
            /** Format: date-time */
            endedAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ListEncountersResponse: {
            data?: components["schemas"]["Encounter"][];
            total?: number;
        };
        LabPrepSaveRequest: {
            specimenType?: string | null;
            /** Format: date-time */
            collectedAt?: string | null;
            collectorName?: string | null;
            /** Format: date-time */
            receivedAt?: string | null;
        };
        RadPrepSaveRequest: {
            fastingRequired?: boolean | null;
            fastingConfirmed?: boolean | null;
            contrastPlanned?: boolean | null;
            creatinineChecked?: boolean | null;
            pregnancyScreenDone?: boolean | null;
            notes?: string | null;
        };
        OpdPrepSaveRequest: {
            systolicBp?: number | null;
            diastolicBp?: number | null;
            pulse?: number | null;
            temperatureC?: number | null;
            respiratoryRate?: number | null;
            weightKg?: number | null;
            spo2?: number | null;
            triageNotes?: string | null;
        };
        /** @enum {string} */
        BbUrgency: "ROUTINE" | "URGENT";
        /** @enum {string} */
        BbCrossmatchResult: "COMPATIBLE" | "INCOMPATIBLE";
        BbPrepSaveRequest: {
            /** Format: date-time */
            sampleReceivedAt?: string | null;
            aboGroup?: string | null;
            rhType?: string | null;
            componentRequested?: string | null;
            unitsRequested?: number | null;
            urgency?: components["schemas"]["BbUrgency"] | null;
        };
        IpdPrepSaveRequest: {
            admissionReason?: string | null;
            ward?: string | null;
            bed?: string | null;
            admittingNotes?: string | null;
        };
        LabMainSaveRequest: {
            resultSummary?: string | null;
            verifiedBy?: string | null;
            /** Format: date-time */
            verifiedAt?: string | null;
        };
        RadMainSaveRequest: {
            reportText?: string | null;
            impression?: string | null;
            radiologistName?: string | null;
            /** Format: date-time */
            reportedAt?: string | null;
        };
        OpdMainSaveRequest: {
            chiefComplaint?: string | null;
            assessment?: string | null;
            plan?: string | null;
            prescriptionText?: string | null;
        };
        BbMainSaveRequest: {
            crossmatchResult?: components["schemas"]["BbCrossmatchResult"] | null;
            componentIssued?: string | null;
            unitsIssued?: number | null;
            /** Format: date-time */
            issuedAt?: string | null;
            issueNotes?: string | null;
        };
        IpdMainSaveRequest: {
            dailyNote?: string | null;
            orders?: string | null;
        };
        EncounterPrepResponse: {
            encounterId: string;
            /** @enum {string} */
            type: "LAB" | "RAD" | "OPD" | "BB" | "IPD";
            /** Format: date-time */
            updatedAt: string | null;
            labPrep: components["schemas"]["LabPrepSaveRequest"] | null;
            radPrep: components["schemas"]["RadPrepSaveRequest"] | null;
            opdPrep: components["schemas"]["OpdPrepSaveRequest"] | null;
            bbPrep: components["schemas"]["BbPrepSaveRequest"] | null;
            ipdPrep: components["schemas"]["IpdPrepSaveRequest"] | null;
        };
        EncounterMainResponse: {
            encounterId: string;
            /** @enum {string} */
            type: "LAB" | "RAD" | "OPD" | "BB" | "IPD";
            /** Format: date-time */
            updatedAt: string | null;
            labMain: components["schemas"]["LabMainSaveRequest"] | null;
            radMain: components["schemas"]["RadMainSaveRequest"] | null;
            opdMain: components["schemas"]["OpdMainSaveRequest"] | null;
            bbMain: components["schemas"]["BbMainSaveRequest"] | null;
            ipdMain: components["schemas"]["IpdMainSaveRequest"] | null;
        };
        /** @enum {string} */
        DocumentType: "ENCOUNTER_SUMMARY" | "LAB_REPORT" | "RAD_REPORT" | "OPD_CLINICAL_NOTE" | "BB_TRANSFUSION_NOTE" | "IPD_DISCHARGE_SUMMARY";
        /**
         * @example {
         *       "documentType": "LAB_REPORT"
         *     }
         */
        DocumentCommandRequest: {
            documentType?: components["schemas"]["DocumentType"];
        };
        DocumentPayloadSample: {
            [key: string]: unknown;
        };
        DocumentPayloadSampleFixtures: {
            ENCOUNTER_SUMMARY: components["schemas"]["DocumentPayloadSample"];
            LAB_REPORT: components["schemas"]["DocumentPayloadSample"];
            RAD_REPORT: components["schemas"]["DocumentPayloadSample"];
            OPD_CLINICAL_NOTE: components["schemas"]["DocumentPayloadSample"];
            BB_TRANSFUSION_NOTE: components["schemas"]["DocumentPayloadSample"];
            IPD_DISCHARGE_SUMMARY: components["schemas"]["DocumentPayloadSample"];
        };
        /** @enum {string} */
        DocumentStatus: "QUEUED" | "RENDERED" | "FAILED";
        DocumentResponse: {
            id: string;
            type: components["schemas"]["DocumentType"];
            status: components["schemas"]["DocumentStatus"];
            encounterId: string;
            payloadHash: string;
            pdfHash?: string | null;
            /** @example 1 */
            payloadVersion: number;
            /** @example 1 */
            templateVersion: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            renderedAt?: string | null;
            errorCode?: string | null;
            errorMessage?: string | null;
        };
        ValidationErrorEnvelope: {
            error: {
                /** @enum {string} */
                type: "validation_error";
                fields: {
                    [key: string]: string[];
                };
            };
        };
        DomainErrorEnvelope: {
            error: {
                /** @enum {string} */
                type: "domain_error";
                code: string;
                message: string;
            };
        };
        AuthErrorEnvelope: {
            error: {
                /** @enum {string} */
                type: "auth_error";
                message: string;
            };
        };
        NotFoundErrorEnvelope: {
            error: {
                /** @enum {string} */
                type: "not_found";
                message: string;
            };
        };
        UnexpectedErrorEnvelope: {
            error: {
                /** @enum {string} */
                type: "unexpected_error";
                message: string;
                correlationId?: string;
            };
        };
    };
    responses: {
        /** @description Structured validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorEnvelope"];
            };
        };
        /** @description Structured domain rule error */
        DomainError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DomainErrorEnvelope"];
            };
        };
        /** @description Authentication or authorization error */
        AuthError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthErrorEnvelope"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["NotFoundErrorEnvelope"];
            };
        };
        /** @description Unexpected server-side failure */
        UnexpectedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UnexpectedErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
        TenantIdHeader: string;
        IdPathParam: string;
        DocumentIdPathParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken?: string;
                        user?: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    getMyFeatures: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature flags map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    listPatients: {
        parameters: {
            query?: {
                query?: string;
                page?: number;
            };
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of patients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPatientsResponse"];
                };
            };
            500: components["responses"]["UnexpectedError"];
        };
    };
    createPatient: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePatientDto"];
            };
        };
        responses: {
            /** @description Patient created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getPatientById: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Patient resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    listEncounters: {
        parameters: {
            query?: {
                page?: number;
                patientId?: string;
                type?: string;
                status?: string;
            };
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of encounters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEncountersResponse"];
                };
            };
            500: components["responses"]["UnexpectedError"];
        };
    };
    createEncounter: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEncounterDto"];
            };
        };
        responses: {
            /** @description Encounter created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Encounter"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getEncounterById: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encounter resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Encounter"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getEncounterPrep: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encounter prep data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterPrepResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getEncounterMain: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encounter main data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterMainResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    startEncounterPrep: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encounter transition result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Encounter"];
                };
            };
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    saveEncounterPrep: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabPrepSaveRequest"] | components["schemas"]["RadPrepSaveRequest"] | components["schemas"]["OpdPrepSaveRequest"] | components["schemas"]["BbPrepSaveRequest"] | components["schemas"]["IpdPrepSaveRequest"];
            };
        };
        responses: {
            /** @description Encounter prep upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterPrepResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    saveEncounterMain: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabMainSaveRequest"] | components["schemas"]["RadMainSaveRequest"] | components["schemas"]["OpdMainSaveRequest"] | components["schemas"]["BbMainSaveRequest"] | components["schemas"]["IpdMainSaveRequest"];
            };
        };
        responses: {
            /** @description Encounter main upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterMainResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    startEncounterMain: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encounter transition result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Encounter"];
                };
            };
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    finalizeEncounter: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encounter transition result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Encounter"];
                };
            };
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    documentEncounter: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DocumentCommandRequest"];
            };
        };
        responses: {
            /** @description Document queued or already rendered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getDocumentById: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                documentId: components["parameters"]["DocumentIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getDocumentFile: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                documentId: components["parameters"]["DocumentIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF file bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
}
