/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email/password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get feature flags for current user scope */
        get: operations["getMyFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search patients */
        get: operations["listPatients"];
        put?: never;
        /** Register a new patient */
        post: operations["createPatient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get patient by id */
        get: operations["getPatientById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search encounters */
        get: operations["listEncounters"];
        put?: never;
        /** Create encounter */
        post: operations["createEncounter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get encounter by id */
        get: operations["getEncounterById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get billing (invoice and payments) for an encounter */
        get: operations["getEncounterBilling"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a payment for an encounter
         * @description Creates or uses the encounter invoice, adds the payment, returns invoice summary and payments list.
         */
        post: operations["recordEncounterPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lims/commands/updateEncounterPrep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update LAB encounter preparation data */
        post: operations["updateEncounterPrep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lab/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List LAB test definitions */
        get: operations["listLabTests"];
        put?: never;
        /** Create LAB test definition */
        post: operations["createLabTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lab/tests/{testId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get LAB test definition by id */
        get: operations["getLabTestById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lab/tests/{testId}/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List parameters for LAB test definition */
        get: operations["listLabTestParameters"];
        put?: never;
        /** Add parameter to LAB test definition */
        post: operations["addLabTestParameter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lab/verification-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List lab order items pending verification
         * @description Tenant-scoped queue of items with status RESULTS_ENTERED, with patient and test context.
         */
        get: operations["getLabVerificationQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}/prep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get encounter prep data */
        get: operations["getEncounterPrep"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}/main": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get encounter main data */
        get: operations["getEncounterMain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:start-prep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start encounter preparation */
        post: operations["startEncounterPrep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:save-prep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save encounter prep data by encounter type */
        post: operations["saveEncounterPrep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:save-main": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save encounter main data by encounter type */
        post: operations["saveEncounterMain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:start-main": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start encounter main workflow */
        post: operations["startEncounterMain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize encounter */
        post: operations["finalizeEncounter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate/publish encounter document */
        post: operations["documentEncounter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:lab-add-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a catalog test to LAB encounter */
        post: operations["addLabTestToEncounter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}/lab-tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ordered LAB tests with parameters and results for encounter */
        get: operations["listEncounterLabTests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:lab-enter-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enter structured results for LAB encounter order item */
        post: operations["enterEncounterLabResults"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:lab-verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify LAB order item results */
        post: operations["verifyEncounterLabResults"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/encounters/{id}:lab-publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish LAB report (PDF-only) for finalized LAB encounter */
        post: operations["publishEncounterLabReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get document metadata by id */
        get: operations["getDocumentById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentId}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download rendered PDF bytes */
        get: operations["getDocumentFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tenant admin overview
         * @description Counts by derived status, verification queue count, published last 24h, PDF health, catalog, feature flags.
         */
        get: operations["getAdminOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id?: string;
            email?: string;
            name?: string;
            tenantId?: string;
        };
        CreatePatientDto: {
            name: string;
            /** Format: date */
            dob?: string;
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            phone?: string;
            fatherOrHusbandName?: string;
            cnic?: string;
            address?: string;
        };
        Patient: components["schemas"]["CreatePatientDto"] & {
            id: string;
            /** @example REG-00000001 */
            regNo: string;
            tenantId?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ListPatientsResponse: {
            data?: components["schemas"]["Patient"][];
            total?: number;
        };
        CreateEncounterDto: {
            /** Format: uuid */
            patientId: string;
            /** @enum {string} */
            type: "LAB" | "RAD" | "OPD" | "BB" | "IPD";
            /** Format: date-time */
            startedAt?: string;
        };
        Encounter: components["schemas"]["CreateEncounterDto"] & {
            id: string;
            tenantId: string;
            /** @example OPD-2026-000001 */
            encounterCode: string;
            /** @enum {string} */
            status: "CREATED" | "PREP" | "IN_PROGRESS" | "FINALIZED" | "DOCUMENTED";
            /**
             * @description Derived lab encounter status (present for LAB encounters only)
             * @enum {string}
             */
            labEncounterStatus?: "DRAFT" | "ORDERED" | "RESULTS_ENTERED" | "VERIFIED" | "PUBLISHED";
            /** @description LAB preparation completion flag. True when required prep data is saved. */
            prep_complete?: boolean;
            /** Format: date-time */
            endedAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ListEncountersResponse: {
            data?: components["schemas"]["Encounter"][];
            total?: number;
        };
        RecordPaymentRequest: {
            amount: number;
            /** @enum {string} */
            method: "CASH" | "CARD" | "ONLINE" | "OTHER";
            reference?: string;
            notes?: string;
        };
        InvoiceSummary: {
            invoice_id: string;
            encounter_id: string;
            total_amount: number;
            paid_amount: number;
            /** @enum {string} */
            status: "UNPAID" | "PARTIAL" | "PAID";
        };
        PaymentRecord: {
            id?: string;
            amount?: number;
            method?: string;
            /** Format: date-time */
            receivedAt?: string;
            reference?: string;
        };
        RecordPaymentResponse: {
            invoice: components["schemas"]["InvoiceSummary"];
            payments: components["schemas"]["PaymentRecord"][];
        };
        UpdateEncounterPrepPayload: {
            /** Format: date-time */
            sample_collected_at: string;
            /** Format: date-time */
            sample_received_at?: string;
            notes?: string;
        };
        UpdateEncounterPrepCommandRequest: {
            /** Format: uuid */
            encounter_id: string;
            prep: components["schemas"]["UpdateEncounterPrepPayload"];
        };
        VerificationQueueItemPatient: {
            patient_id?: string;
            mrn?: string;
            name?: string;
            age?: number;
            sex?: string;
        };
        VerificationQueueItemTest: {
            test_code?: string;
            test_name?: string;
        };
        VerificationQueueItem: {
            encounter_id?: string;
            lab_order_item_id?: string;
            /** @enum {string} */
            derived_encounter_status?: "DRAFT" | "ORDERED" | "RESULTS_ENTERED" | "VERIFIED" | "PUBLISHED";
            patient?: components["schemas"]["VerificationQueueItemPatient"];
            test?: components["schemas"]["VerificationQueueItemTest"];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            results_entered_at?: string;
        };
        VerificationQueueResponse: {
            items: components["schemas"]["VerificationQueueItem"][];
        };
        AdminOverviewCounts: {
            /** @description Map of derived lab encounter status to count */
            encounters_by_status?: {
                [key: string]: number;
            };
            verification_queue_count?: number;
            published_last_24h_count?: number;
        };
        AdminOverviewSystem: {
            pdf_service_health?: {
                /** @enum {string} */
                status?: "ok" | "degraded";
                /** Format: date-time */
                last_checked_at?: string;
            };
        };
        AdminOverviewCatalog: {
            tests_count?: number;
            parameters_count?: number;
        };
        AdminOverviewResponse: {
            counts: components["schemas"]["AdminOverviewCounts"];
            system: components["schemas"]["AdminOverviewSystem"];
            catalog: components["schemas"]["AdminOverviewCatalog"];
            /** @description Enabled feature flags for tenant */
            features: {
                [key: string]: boolean;
            };
        };
        LabTestDefinition: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            department: string;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        LabTestParameter: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            testId: string;
            name: string;
            unit?: string | null;
            refLow?: number | null;
            refHigh?: number | null;
            refText?: string | null;
            displayOrder: number;
            active: boolean;
        };
        /** @enum {string} */
        LabOrderItemStatus: "ORDERED" | "RESULTS_ENTERED" | "VERIFIED";
        /** @enum {string} */
        LabResultFlag: "LOW" | "HIGH" | "NORMAL" | "ABNORMAL" | "UNKNOWN";
        LabOrderItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            encounterId: string;
            /** Format: uuid */
            testId: string;
            status: components["schemas"]["LabOrderItemStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        LabResultItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderItemId: string;
            /** Format: uuid */
            parameterId: string;
            value: string;
            valueNumeric?: number | null;
            flag: components["schemas"]["LabResultFlag"];
            enteredBy?: string | null;
            /** Format: date-time */
            enteredAt?: string | null;
            verifiedBy?: string | null;
            /** Format: date-time */
            verifiedAt?: string | null;
        };
        LabOrderedTest: {
            orderItem: components["schemas"]["LabOrderItem"];
            test: components["schemas"]["LabTestDefinition"];
            parameters: components["schemas"]["LabTestParameter"][];
            results: components["schemas"]["LabResultItem"][];
        };
        ListLabTestsResponse: {
            data: components["schemas"]["LabTestDefinition"][];
            total: number;
        };
        ListLabTestParametersResponse: {
            data: components["schemas"]["LabTestParameter"][];
            total: number;
        };
        ListEncounterLabTestsResponse: {
            data: components["schemas"]["LabOrderedTest"][];
            total: number;
        };
        CreateTestRequest: {
            code: string;
            name: string;
            department: string;
            active?: boolean;
        };
        AddParameterRequest: {
            name: string;
            unit?: string;
            refLow?: number;
            refHigh?: number;
            refText?: string;
            displayOrder?: number;
            active?: boolean;
        };
        AddTestToEncounterRequest: {
            /** Format: uuid */
            testId: string;
        };
        EnterLabResultValueInput: {
            /** Format: uuid */
            parameterId: string;
            value: string;
        };
        EnterLabResultsRequest: {
            /** Format: uuid */
            orderItemId: string;
            results: components["schemas"]["EnterLabResultValueInput"][];
        };
        VerifyLabResultsRequest: {
            /** Format: uuid */
            orderItemId: string;
        };
        LabPrepSaveRequest: {
            specimenType?: string | null;
            /** Format: date-time */
            collectedAt?: string | null;
            collectorName?: string | null;
            /** Format: date-time */
            receivedAt?: string | null;
        };
        RadPrepSaveRequest: {
            fastingRequired?: boolean | null;
            fastingConfirmed?: boolean | null;
            contrastPlanned?: boolean | null;
            creatinineChecked?: boolean | null;
            pregnancyScreenDone?: boolean | null;
            notes?: string | null;
        };
        OpdPrepSaveRequest: {
            systolicBp?: number | null;
            diastolicBp?: number | null;
            pulse?: number | null;
            temperatureC?: number | null;
            respiratoryRate?: number | null;
            weightKg?: number | null;
            spo2?: number | null;
            triageNotes?: string | null;
        };
        /** @enum {string} */
        BbUrgency: "ROUTINE" | "URGENT";
        /** @enum {string} */
        BbCrossmatchResult: "COMPATIBLE" | "INCOMPATIBLE";
        BbPrepSaveRequest: {
            /** Format: date-time */
            sampleReceivedAt?: string | null;
            aboGroup?: string | null;
            rhType?: string | null;
            componentRequested?: string | null;
            unitsRequested?: number | null;
            urgency?: components["schemas"]["BbUrgency"] | null;
        };
        IpdPrepSaveRequest: {
            admissionReason?: string | null;
            ward?: string | null;
            bed?: string | null;
            admittingNotes?: string | null;
        };
        LabMainSaveRequest: {
            resultSummary?: string | null;
            verifiedBy?: string | null;
            /** Format: date-time */
            verifiedAt?: string | null;
        };
        RadMainSaveRequest: {
            reportText?: string | null;
            impression?: string | null;
            radiologistName?: string | null;
            /** Format: date-time */
            reportedAt?: string | null;
        };
        OpdMainSaveRequest: {
            chiefComplaint?: string | null;
            assessment?: string | null;
            plan?: string | null;
            prescriptionText?: string | null;
        };
        BbMainSaveRequest: {
            crossmatchResult?: components["schemas"]["BbCrossmatchResult"] | null;
            componentIssued?: string | null;
            unitsIssued?: number | null;
            /** Format: date-time */
            issuedAt?: string | null;
            issueNotes?: string | null;
        };
        IpdMainSaveRequest: {
            dailyNote?: string | null;
            orders?: string | null;
        };
        EncounterPrepResponse: {
            encounterId: string;
            /** @enum {string} */
            type: "LAB" | "RAD" | "OPD" | "BB" | "IPD";
            /** Format: date-time */
            updatedAt: string | null;
            labPrep: components["schemas"]["LabPrepSaveRequest"] | null;
            radPrep: components["schemas"]["RadPrepSaveRequest"] | null;
            opdPrep: components["schemas"]["OpdPrepSaveRequest"] | null;
            bbPrep: components["schemas"]["BbPrepSaveRequest"] | null;
            ipdPrep: components["schemas"]["IpdPrepSaveRequest"] | null;
        };
        EncounterMainResponse: {
            encounterId: string;
            /** @enum {string} */
            type: "LAB" | "RAD" | "OPD" | "BB" | "IPD";
            /** Format: date-time */
            updatedAt: string | null;
            labMain: components["schemas"]["LabMainSaveRequest"] | null;
            radMain: components["schemas"]["RadMainSaveRequest"] | null;
            opdMain: components["schemas"]["OpdMainSaveRequest"] | null;
            bbMain: components["schemas"]["BbMainSaveRequest"] | null;
            ipdMain: components["schemas"]["IpdMainSaveRequest"] | null;
        };
        /** @enum {string} */
        DocumentType: "ENCOUNTER_SUMMARY_V1" | "LAB_REPORT_V1" | "OPD_SUMMARY_V1" | "RAD_REPORT_V1" | "BB_ISSUE_SLIP_V1" | "IPD_SUMMARY_V1";
        /**
         * @example {
         *       "documentType": "LAB_REPORT_V1"
         *     }
         */
        DocumentCommandRequest: {
            documentType: components["schemas"]["DocumentType"];
        };
        DocumentPayloadSample: {
            [key: string]: unknown;
        };
        DocumentPayloadSampleFixtures: {
            ENCOUNTER_SUMMARY_V1: components["schemas"]["DocumentPayloadSample"];
            LAB_REPORT_V1: components["schemas"]["DocumentPayloadSample"];
            OPD_SUMMARY_V1: components["schemas"]["DocumentPayloadSample"];
            RAD_REPORT_V1: components["schemas"]["DocumentPayloadSample"];
            BB_ISSUE_SLIP_V1: components["schemas"]["DocumentPayloadSample"];
            IPD_SUMMARY_V1: components["schemas"]["DocumentPayloadSample"];
        };
        /** @enum {string} */
        DocumentStatus: "QUEUED" | "RENDERED" | "FAILED";
        DocumentResponse: {
            id: string;
            type: components["schemas"]["DocumentType"];
            /** @example RAD_REPORT_V1 */
            templateKey: string;
            status: components["schemas"]["DocumentStatus"];
            encounterId: string;
            payloadHash: string;
            pdfHash?: string | null;
            /** @example 1 */
            payloadVersion: number;
            /** @example 1 */
            templateVersion: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            renderedAt?: string | null;
            errorCode?: string | null;
            errorMessage?: string | null;
        };
        ValidationErrorEnvelope: {
            error: {
                /** @enum {string} */
                type: "validation_error";
                fields: {
                    [key: string]: string[];
                };
            };
        };
        DomainErrorEnvelope: {
            error: {
                /** @enum {string} */
                type: "domain_error";
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        AuthErrorEnvelope: {
            error: {
                /** @enum {string} */
                type: "auth_error";
                message: string;
            };
        };
        NotFoundErrorEnvelope: {
            error: {
                /** @enum {string} */
                type: "not_found";
                message: string;
            };
        };
        UnexpectedErrorEnvelope: {
            error: {
                /** @enum {string} */
                type: "unexpected_error";
                message: string;
                correlationId?: string;
            };
        };
    };
    responses: {
        /** @description Structured validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorEnvelope"];
            };
        };
        /** @description Structured domain rule error */
        DomainError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DomainErrorEnvelope"];
            };
        };
        /** @description Authentication or authorization error */
        AuthError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthErrorEnvelope"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["NotFoundErrorEnvelope"];
            };
        };
        /** @description Unexpected server-side failure */
        UnexpectedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UnexpectedErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
        TenantIdHeader: string;
        IdPathParam: string;
        DocumentIdPathParam: string;
        LabTestIdPathParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken?: string;
                        user?: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    getMyFeatures: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature flags map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            401: components["responses"]["AuthError"];
        };
    };
    listPatients: {
        parameters: {
            query?: {
                query?: string;
                page?: number;
            };
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of patients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPatientsResponse"];
                };
            };
            500: components["responses"]["UnexpectedError"];
        };
    };
    createPatient: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePatientDto"];
            };
        };
        responses: {
            /** @description Patient created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getPatientById: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Patient resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    listEncounters: {
        parameters: {
            query?: {
                page?: number;
                patientId?: string;
                type?: string;
                status?: string;
            };
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of encounters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEncountersResponse"];
                };
            };
            500: components["responses"]["UnexpectedError"];
        };
    };
    createEncounter: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEncounterDto"];
            };
        };
        responses: {
            /** @description Encounter created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Encounter"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["AuthError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getEncounterById: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encounter resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Encounter"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getEncounterBilling: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice and payments, or null if no invoice exists yet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["RecordPaymentResponse"] | null) | null;
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    recordEncounterPayment: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordPaymentRequest"];
            };
        };
        responses: {
            /** @description Invoice and payments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordPaymentResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    updateEncounterPrep: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEncounterPrepCommandRequest"];
            };
        };
        responses: {
            /** @description Updated encounter snapshot with preparation status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Encounter"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["AuthError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    listLabTests: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LAB test list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListLabTestsResponse"];
                };
            };
            500: components["responses"]["UnexpectedError"];
        };
    };
    createLabTest: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTestRequest"];
            };
        };
        responses: {
            /** @description LAB test created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabTestDefinition"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getLabTestById: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                testId: components["parameters"]["LabTestIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LAB test definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabTestDefinition"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    listLabTestParameters: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                testId: components["parameters"]["LabTestIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LAB parameters list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListLabTestParametersResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    addLabTestParameter: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                testId: components["parameters"]["LabTestIdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddParameterRequest"];
            };
        };
        responses: {
            /** @description LAB parameter created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabTestParameter"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["AuthError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getLabVerificationQueue: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                from?: string;
                to?: string;
            };
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification queue items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationQueueResponse"];
                };
            };
            500: components["responses"]["UnexpectedError"];
        };
    };
    getEncounterPrep: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encounter prep data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterPrepResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getEncounterMain: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encounter main data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterMainResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    startEncounterPrep: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encounter transition result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Encounter"];
                };
            };
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    saveEncounterPrep: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabPrepSaveRequest"] | components["schemas"]["RadPrepSaveRequest"] | components["schemas"]["OpdPrepSaveRequest"] | components["schemas"]["BbPrepSaveRequest"] | components["schemas"]["IpdPrepSaveRequest"];
            };
        };
        responses: {
            /** @description Encounter prep upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterPrepResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["AuthError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    saveEncounterMain: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabMainSaveRequest"] | components["schemas"]["RadMainSaveRequest"] | components["schemas"]["OpdMainSaveRequest"] | components["schemas"]["BbMainSaveRequest"] | components["schemas"]["IpdMainSaveRequest"];
            };
        };
        responses: {
            /** @description Encounter main upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterMainResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["AuthError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    startEncounterMain: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encounter transition result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Encounter"];
                };
            };
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    finalizeEncounter: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encounter transition result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Encounter"];
                };
            };
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    documentEncounter: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCommandRequest"];
            };
        };
        responses: {
            /** @description Document queued or already rendered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["AuthError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    addLabTestToEncounter: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTestToEncounterRequest"];
            };
        };
        responses: {
            /** @description LAB order item created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabOrderedTest"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["AuthError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    listEncounterLabTests: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered LAB tests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEncounterLabTestsResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    enterEncounterLabResults: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnterLabResultsRequest"];
            };
        };
        responses: {
            /** @description Results entered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabOrderedTest"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    verifyEncounterLabResults: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyLabResultsRequest"];
            };
        };
        responses: {
            /** @description LAB order item verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabOrderedTest"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    publishEncounterLabReport: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LAB report queued or rendered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getDocumentById: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                documentId: components["parameters"]["DocumentIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getDocumentFile: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path: {
                documentId: components["parameters"]["DocumentIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF file bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["DomainError"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    getAdminOverview: {
        parameters: {
            query?: never;
            header?: {
                /** @description DEV ONLY. Ignored in production. For local testing when hostname is localhost. */
                "x-tenant-id"?: components["parameters"]["TenantIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOverviewResponse"];
                };
            };
            500: components["responses"]["UnexpectedError"];
        };
    };
}
